### ISSUE TITLE
Chrome 103 - The script is not trigger until you quit chrome

### ISSUE THREAD

**Issue by behrooz-tahanzadeh** [danielnitz/zebra-printing-chrome-extension#3] opened 2022-06-22 14:13 UTC
I can only see the `content.js loaded` message in the console. I've been testing this on Mac but I believe it behaves the same on windows.
The message is triggered only when I quit chrome.

**Comment by danielnitz** [comment] 2024-09-25 10:32
I cannot reproduce this issue. Considering the time that has passed, I'll close this. Feel free to open a new ticket if this is still an issue for you.

**Closed by danielnitz** 2024-09-25 10:32 UTC
